name: flutter_openart_nft
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  get: ^4.6.6
  flutter_svg: ^2.0.10+1
  gradient_borders: ^1.0.1
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/bitmap/
    - assets/fonts/
    - assets/vector/

  fonts:
    - family: Epilogue
      fonts:
        - asset: assets/fonts/Epilogue-Thin.ttf
          weight: 100
        - asset: assets/fonts/Epilogue-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Epilogue-Light.ttf
          weight: 300
        - asset: assets/fonts/Epilogue-Regular.ttf
          weight: 400
        - asset: assets/fonts/Epilogue-Medium.ttf
          weight: 500
        - asset: assets/fonts/Epilogue-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Epilogue-Bold.ttf
          weight: 700
        - asset: assets/fonts/Epilogue-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Epilogue-Black.ttf
          weight: 900
